name: Publish new version
on:
    push:
        branches:
            - main
jobs:
    publish-docker:
        name: Publish Docker image to DockerHub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Load current version into the environment
              run: echo 'VERSION=$(node -p \'require(\\'./package.json\\').version\')' >>
                  $GITHUB_ENV
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: hejny/promptbook:${{ env.VERSION }}
